[build]
  publish = "public"
  command = '''
  ls -al $NETLIFY_CACHE_DIR
  yarn gatsby build
  '''
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.7.0"
  YARN_FLAGS = "--no-ignore-optional --pure-lockfile"
